
yaml
Copy
Edit
name: Build, Test and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with version tag and latest
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:latest

      - name: Push Docker image with version tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:${{ github.sha }}

      - name: Push Docker image with latest tag
        run: docker push ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:latest