
name: Build, Test and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:latest
         
  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: SSH to server and deploy
          uses: appleboy/ssh-action@v1.0.0
          with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SERVER_USER }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:latest
            docker stop jobtrackingapi || true
            docker rm jobtrackingapi || true
            docker run -d -p 8080:80 --name jobtrackingapi \
              -e Jwt__Key=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_USERNAME }}/jobtrackingapi:latest 

